"""Meeting summary display panel."""

from PyQt6.QtCore import pyqtSignal
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QTextEdit, QPushButton, QHBoxLayout, QLabel,
    QApplication, QLineEdit,
)

from app.ui.vertical_resize_grip import VerticalResizeGrip


def _format_seconds(seconds):
    """Compact duration for the provenance line: '4.2s' or '1m 5s'."""
    seconds = float(seconds)
    if seconds < 60:
        return f"{seconds:.1f}s"
    m = int(seconds // 60)
    s = int(round(seconds % 60))
    return f"{m}m {s}s"


class SummaryPanel(QWidget):
    regenerate_requested = pyqtSignal()
    delete_requested = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self._setup_ui()

    def _setup_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)

        self._status = QLabel("No summary generated yet.")
        self._status.setObjectName("summaryStatus")
        layout.addWidget(self._status)

        # Provenance: which model produced this summary and how long it took.
        self._meta_label = QLabel("")
        self._meta_label.setObjectName("summaryMetaLabel")
        self._meta_label.setVisible(False)
        layout.addWidget(self._meta_label)

        self._text = QTextEdit()
        self._text.setObjectName("summaryTextEdit")
        self._text.setReadOnly(False)
        self._text.setFixedHeight(220)
        self._text.setVisible(False)
        layout.addWidget(self._text)

        self._resize_grip = VerticalResizeGrip(self._text, min_height=100, max_height=640)
        self._resize_grip.setVisible(False)
        layout.addWidget(self._resize_grip)

        # Instruction input for regeneration
        self._instruction_input = QLineEdit()
        self._instruction_input.setObjectName("summaryInstructionInput")
        self._instruction_input.setPlaceholderText(
            "Optional: instructions for regeneration (e.g. \"use John instead of SPEAKER_00\")"
        )
        self._instruction_input.setVisible(False)
        layout.addWidget(self._instruction_input)

        btn_row = QHBoxLayout()
        self._copy_btn = QPushButton("Copy")
        self._copy_btn.clicked.connect(self._copy)
        self._copy_btn.setVisible(False)
        btn_row.addWidget(self._copy_btn)

        self._gen_btn = QPushButton("Generate Summary")
        self._gen_btn.clicked.connect(self.regenerate_requested.emit)
        self._gen_btn.setVisible(False)
        btn_row.addWidget(self._gen_btn)

        # Wipes both the summary and the action items for this recording.
        self._delete_btn = QPushButton("Delete")
        self._delete_btn.setObjectName("summaryDeleteBtn")
        self._delete_btn.clicked.connect(self.delete_requested.emit)
        self._delete_btn.setVisible(False)
        btn_row.addWidget(self._delete_btn)

        btn_row.addStretch()
        layout.addLayout(btn_row)

    def set_summary(self, text):
        self._text.setMarkdown(text)
        self._text.setVisible(True)
        self._resize_grip.setVisible(True)
        self._copy_btn.setVisible(True)
        self._gen_btn.setText("Regenerate")
        self._gen_btn.setVisible(True)
        self._delete_btn.setVisible(True)
        self._instruction_input.setVisible(True)
        self._status.setVisible(False)

    def set_meta(self, model="", seconds=None):
        """Show 'Generated by <model> in <time>'. Called after set_summary on
        both a fresh generation and on load; a missing model/time hides it."""
        if not model and not seconds:
            self._meta_label.clear()
            self._meta_label.setVisible(False)
            return
        parts = []
        if model:
            parts.append(f"Generated by {model}")
        if seconds:
            parts.append(f"in {_format_seconds(seconds)}")
        self._meta_label.setText(" ".join(parts))
        self._meta_label.setVisible(True)

    def clear(self):
        """Reset to initial empty state."""
        self.set_meta()
        self._text.clear()
        self._text.setVisible(False)
        self._resize_grip.setVisible(False)
        self._copy_btn.setVisible(False)
        self._gen_btn.setVisible(False)
        self._delete_btn.setVisible(False)
        self._instruction_input.clear()
        self._instruction_input.setVisible(False)
        self._status.setText("No summary generated yet.")
        self._status.setVisible(True)

    def set_ready(self):
        """Show generate button when a transcript is available but no summary yet."""
        if not self._text.isVisible():
            self._gen_btn.setText("Generate Summary")
            self._gen_btn.setVisible(True)

    def set_loading(self):
        # Neutral: the phase verb ("Generating summary") and its elapsed clock
        # live on the shared activity strip now, so this panel just shows that
        # something is running.
        self._status.setText("Working…")
        self._status.setVisible(True)
        self._meta_label.setVisible(False)
        self._gen_btn.setVisible(False)
        self._delete_btn.setVisible(False)
        self._instruction_input.setVisible(False)
        self._text.setVisible(False)
        self._resize_grip.setVisible(False)

    def set_error(self, message="Summary generation failed."):
        """Restore from the loading state after a failed generation."""
        if self._text.toPlainText():
            # A previous summary exists — bring it back.
            self._text.setVisible(True)
            self._resize_grip.setVisible(True)
            self._copy_btn.setVisible(True)
            self._delete_btn.setVisible(True)
            self._instruction_input.setVisible(True)
            self._status.setVisible(False)
            self._gen_btn.setText("Regenerate")
        else:
            self._status.setText(message)
            self._status.setVisible(True)
            self._gen_btn.setText("Generate Summary")
        self._gen_btn.setVisible(True)

    def get_text(self):
        return self._text.toPlainText()

    def get_instruction(self):
        """Return the user's regeneration instruction, if any."""
        return self._instruction_input.text().strip()

    def _copy(self):
        QApplication.clipboard().setText(self._text.toPlainText())
